#!/bin/sh

repo="https://github.com/theblacksmith/yii-boilerplate.git"
project=""
template=""

function usage
{
	echo "\nYii-boilerplate (by theblacksmith)\n\n"
    echo "Usage:"
    echo "  yiib TEMPLATE PROJECT_NAME\n\n"
	echo "Available templates"
	echo "  master"
	echo "  haml"
	echo "  bootstrap"
}

function create_project
{
	echo "Creating project directory"
	mkdir $project
	
	echo "Cloning template"
	git clone -b $template $repo $project
	
	echo "Removing the origin"
	cd $project
	git remote rm origin
	cd ..
	
	echo "done!"
}

if [ $# = 2 ]; then
	template=$1
	project=$2
    create_project
else
    usage
fi

